project:
  type: website
  lib-dir: site_libs
  render:
    - index.qmd
    - slides/*.qmd

execute:
  freeze: auto

editor: source

website:
  title: "InsightNet EpiData Workshop 2024"
  page-footer:
    center: "This work by the [Delphi Research Group](https://delphi.cmu.edu) is licensed under the [MIT license](LICENSE.md)."
  navbar:
    pinned: false
    title: "<i class='bi bi-graph-down'></i> InsightNet Workshop 2024"
    right:
      - text: Delphi
        url: https://delphi.cmu.edu/
      - text: GitHub
        url: https://github.com/cmu-delphi/insightnet-workshop-2024
        icon: github


format:
  html:
    theme: [cosmo, assets/styles.scss]
    page-layout: custom
